{
	"version": 1683339223,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite7-sheet1.png",
		"images/tiledbackground.png",
		"images/sprite8-sheet0.png",
		"images/particles.png",
		"images/particles2.png",
		"images/sprite9-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/tiledbackground2.png",
		"media/jdb_secrets_2.ogg",
		"media/1brick.ogg",
		"media/1paddle.ogg",
		"media/1wall.ogg",
		"media/jdb artist - inspirational vol.2 - 15 challenge (modern).ogg",
		"media/jdb artist - inspirational vol.2 - 14 burning engines (modern).ogg",
		"media/jdb artist - inspirational vol.2 - 16 faster than light (modern).ogg",
		"media/jdb artist - inspirational vol.2 - 18 digital frontier (modern).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"penumbra.png"
	]
}